- name: create jenkins jobs
  hosts: localhost
  roles:
   - jenkins
  vars:
    folders:
      - {folder_name: "CI_Pipeline"}
    mjobs:
      - { job_name: "cart", repo_name: "https://github.com/shaikusmandevops/cart", folder_name: "CI_Pipeline" }
    sjobs:
      - { job_name: "roboshop-terraform", repo_name: "https://github.com/shaikusmandevops/aws-terraform", folder_name: "CI_Pipeline"}
