- name: Create Jenkins Jobs
  hosts: localhost
  roles:
    - jenkins
  vars:
   mjobs:
    - {job_name:"cart", repo_name:"https://github.com/shaikusmandevops/roboshop-jenkins.git" }
   sjobs:
     - {job_name:"roboshop-terraform", repo_name="https://github.com/shaikusmandevops/roboshop-jenkins.git" }