- name: create jenkins jobs
  hosts: local
  roles:
   - jenkins
  vars:
    mjob:
      - {job_name: "cart" , repo_name: "https://github.com/shaikusmandevops/cart.git" }
    sjob:
      - { job_name: "roboshop-terraform", repo_name: "https://github.com/shaikusmandevops/aws-terraform.git"}
