- name: Create Jenkins Jobs
  hosts: localhost
  roles:
    - jenkins
  vars:
   folders:
     - { folder_name: "CI-Pipelines" }
     - { folder_name: "Infra-Jobs" }
   mjobs:
    - {job_name:"cart", repo_name:"https://github.com/shaikusmandevops/roboshop-jenkins.git", folder_name: "CI-Pipelines" }
   sjobs:
     - {job_name:"roboshop-terraform", repo_name="https://github.com/shaikusmandevops/roboshop-jenkins.git" , folder_name: "Infra-Jobs" }