- name: create folder - {{item.folder}}
  ansible.builtin.include_tasks:
      file: folder.yml

- name: create single pipeline job - {{item.job_name}}
  ansible.builtin.include_tasks:
      file: sjob.yml
  loop: "{{ sjob }}"

- name: create multi pipeline job - {{item.job_name}}
  ansible.builtin.include_tasks:
      file: mjob.yml
  loop: "{{ mjob }}"