-create: copy config file - {{ item.job_name }}
  ansible.builtin.templates:
  src: mjob.xml
  dest: /tmp/mjob.xml

- name: Create a jenkins job - {{ item.job_name }}
  community.general.jenkins_job:
  config: "{{ lookup('file', 'templates/mjob.xml') }}"
  name: { { item.job_name } }
  password: admin123
  url: http://23.22.206.213:8080
  user: admin
