- name: Copy mjob config file
  ansible.builtin.template:
    src: mjob.xml
    dest: /tmp/mjob.xml


- name: Create a multi pipeline branch in jenkins - {{items.job_name}}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/mjob.xml') }}"
    name: "{{items.job_name}}"
    password: admin
    url: http://172.31.85.67:8080
    user: admin