- name: Copy mjob config file
  ansible.builtin.template:
    src: mjob.xml
    dest: /tmp/mjob.xml


- name: Create a multi pipeline branch in jenkins - {{item.job_name}}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/mjob.xml') }}"
    name: "{{item.folder_name}}/{{item.job_name}}"
    password: admin123
    url: http://44.203.84.56:8080/
    user: admin