- name: Copy Config File - {{ item.job_name }}
  ansible.builtin.template:
    src: sjob.xml
    dest: /tmp/sjob.xml

- name: Create Job - {{ item.job_name }}
  community.general.jenkins_job:
      config: "{{ lookup('file', 'templates/sjob.xml') }}"
      name: "{{item.folder_name}}/{ { item.job_name } }"
      password: admin
      url: http://44.212.39.222:8080
      user: admin
