- name: Copy sjob config file
  ansible.builtin.template:
    src: sjob.xml
    dest: /tmp/sjob.xml


- name: Create a single pipeline branch in jenkins - {{items.job_name}}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/sjob.xml') }}"
    name: "{{items.job_name}}"
    password: admin
    url: http://54.221.69.10:8080
    user: admin