- name: Copy Config File - {{ item.job_name }}
  ansible.builtin.template:
    src: sjob.xml
    dest: /tmp/sjob.xml

  - name: Create a jenkins job - {{ item.job_name }}
    community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/sjob.xml') }}"
    name: { { item.job_name } }
    password: admin123
    url: http://23.22.206.213:8080
    user: admin