- name: Copy sjob config file
  ansible.builtin.template:
    src: sjob.xml
    dest: /tmp/sjob.xml


- name: Create a single pipeline branch in jenkins - {{item.job_name}}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/sjob.xml') }}"
    name: "{{item.job_name}}"
    password: admin
    url: http://18.209.167.115:8080/
    user: admin